apiVersion: v1
kind: Service
metadata:
  name: illumineer-frontend
spec:
  selector:
    app: illumineer-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
